name: simple-web-server
target: gcp
provisioners:
  - terraform
config:
  gcp: 
    project_id: ${GCP_PROJECT_ID}
    region: us-central1
    zone: us-central1-a
    instance_type: e2-micro
    disk_size: 10
  aws:
    region: ${AWS_REGION}
    instance_type: t2.micro
    disk_size: 10
